### PR TITLE
Update helper.py

### PR DESCRIPTION
**Pull request by tmr232**
Encode Unicode strings coming from jsondocs.

### CODE REVIEW

**Comment by tmr232** [comment]
@fmagin @clearbluejar care to review before I merge?

(That said, the code is already on PyPI 😝 )

**Comment by fmagin** [comment]
Seems sane?

How is the code already on PyPI though, did the publish job accidentally run already?

**Comment by tmr232** [comment]
I ran it to make sure it works, not realizing that it'll also publish 🤦

**Comment by clearbluejar** [comment]
Looks good. How did you generate the new classes.list? Can you add that to the README? Or perhaps we can script it in the workflow.

1. Generate classes.list
2. Commit it before release.

**Comment by tmr232** [comment]
It's a terrible hack...

1. Go the the docs, to the tree-overview page - https://ghidra.re/ghidra_docs/api/overview-tree.html
2. Copy everything under "class hierarchy"
3. Remove the extra text (spaces before names, and anything after names - spaces, `<`, `(`, etc.)

**Comment by clearbluejar** [comment]
> I ran it to make sure it works, not realizing that it'll also publish 🤦

Currently, if the build is successful it will publish to pypi.  We could limit the publish to only publish if a new input flag is set?  It was setup this way so that it would auto publish when a new version of Ghidra went out. We could disable it for manual build from workflow dispatch. 

`if: github.event_name != 'workflow_dispatch'`

**Comment by fmagin** [comment]
Wouldn't constraining it to `main` be the better choice? i.e. a new commit on `main` should lead to a new version being published, and also a scheduled job that runs the latest `main` commit again for the new Ghidra version (if there is one)

**Pull request merged**
